# Generated by Django 6.0.2 on 2026-02-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('bags', 'Crochet Bags'), ('keychains', 'Crochet Keychains'), ('flowers', 'Crochet Flowers'), ('home', 'Home Decor'), ('custom', 'Custom Orders')], max_length=50)),
                ('status', models.CharField(choices=[('coming_soon', 'Coming Soon'), ('featured', 'Featured')], default='coming_soon', max_length=20)),
                ('launch_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
